title: this.xor.that – creative coding and generative art
description: >- 
  Creative coding by this.xor.that.
baseurl: ""
url: "https://thisxorthat.art"

github_username:  jessstringham
permalink: pretty